Areas/Games/Pages/Shared/_KlondikeBoard.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ChapelStudiosWWW.Pages.Games.Partials
{
    public class _KlondikeBoardModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Areas/ResumeBuilder/Controllers/ResumesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChapelStudiosWWW.Areas.ResumeBuilder.Models;
using ChapelStudiosWWW.Data;

namespace ChapelStudiosWWW.Areas.ResumeBuilder.Controllers
{
    [Area("ResumeBuilder")]
    public class ResumesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ResumesController(ApplicationDbContext context)
        {
            this._context = context;
        }

        // GET: ResumeBuilder/Resumes
        public async Task<IActionResult> Index()
        {
            return View(await this._context.Resume.ToListAsync().ConfigureAwait(false));
        }

        // GET: ResumeBuilder/Resumes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                id = 0;
            }

            var resume = await _context.Resume
                .FirstOrDefaultAsync(m => m.LocalId == id).ConfigureAwait(false);
            if (resume == null)
            {
                return NotFound();
            }

            return View(resume);
        }

        // GET: ResumeBuilder/Resumes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ResumeBuilder/Resumes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LocalId,Notes")] Resume resume)
        {
            if (ModelState.IsValid)
            {
                _context.Add(resume);
                await _context.SaveChangesAsync().ConfigureAwait(false);
                return RedirectToAction(nameof(Index));
            }
            return View(resume);
        }

        // GET: ResumeBuilder/Resumes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var resume = await _context.Resume.FindAsync(id);
            if (resume == null)
            {
                return NotFound();
            }
            return View(resume);
        }

        // POST: ResumeBuilder/Resumes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LocalId,Notes")] Resume resume)
        {
            if (id != resume.LocalId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(resume);
                    await _context.SaveChangesAsync().ConfigureAwait(false);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ResumeExists(resume.LocalId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(resume);
        }

        // GET: ResumeBuilder/Resumes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var resume = await _context.Resume
                .FirstOrDefaultAsync(m => m.LocalId == id);
            if (resume == null)
            {
                return NotFound();
            }

            return View(resume);
        }

        // POST: ResumeBuilder/Resumes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var resume = await _context.Resume.FindAsync(id);
            _context.Resume.Remove(resume);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ResumeExists(int id)
        {
            return _context.Resume.Any(e => e.LocalId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using System.Web
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta property="og:title" content="Chapel Studios - @ViewData["Title"]" />
    <meta property="og:image" content="https://www.chapelstudios.dev/Assets/Images/Icons/SmallLogo.jpg" />
    <meta property="og:url" content="https://www.chapelstudios.dev" />

    <title>@ViewData["Title"] - Chapel Studios</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/css/core.css" />
        <script src="~/js/CSTools.js"></script>
    </environment>
    <environment include="Production">
        <link rel="stylesheet" href="~/css/core.css" asp-append-version="true" />
        <script src="~/js/CSTools.min.js" asp-append-version="true"></script>
    </environment>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://kit.fontawesome.com/acfd707b9b.js" crossorigin="anonymous"></script>
    @RenderSection("Head", false)
</head>
<body>
    <header>
        <nav>
            <div class="container">
                <a class="brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <input id="navbar-checkbox" type="checkbox" autocomplete="off" />
                <label for="navbar-checkbox" class="navbar-toggler"><span></span></label>
                <div class="navbar-collapse">
                    <partial name="_Navigation" />
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container content">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <div class="to-top-btn"></div>

    <footer>
        <div class="container">
            <a class="brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
            <ul class="sitemap">
                <li><a asp-page="/Home/Contact">Contact Us</a></li>
                <li><a asp-page="/Home/Team">Our Team</a></li>
                @RenderSection("SiteMap", false)
                <partial name="_LoginFooter" />
                <li><a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
            </ul>
            @RenderSection("Footer", false)
            <div class="copyright">
                &copy; 2020 - Chapel Studios &amp; Jake Blackwell
            </div>
        </div>
    </footer>
    <environment include="Development">
        <script src="~/js/core.js"></script>
    </environment>
    <environment include="Production">
        <script src="~/js/core.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_LoginFooter.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <li>
        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
            <button type="submit">Sign out</button>
        </form>
    </li>
}
else
{
    <li><a class="nav-link" asp-area="Identity" asp-page="/Account/Login">Sign In</a></li>
}

Views/Shared/_Navigation.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@{
    bool isOnHomePage = false;
    if (ViewContext.RouteData.Values["page"] != null)
    {
        isOnHomePage = ViewContext.RouteData.Values["page"].ToString() == "Index";
    }
    else if (ViewContext.RouteData.Values["controller"] != null)
    {
        isOnHomePage = (ViewContext.RouteData.Values["controller"].ToString() == "Home"
                        && ViewContext.RouteData.Values["action"].ToString() == "Index");
    }
    bool showAboutMenu = !SignInManager.IsSignedIn(User) || isOnHomePage;
}

<ul class="nav-main">
    <li class="nav-item">
        <a class="nav-link" href="#">Games</a>
        <ul class="nav-menu">
            <li class="nav-item">
                <a class="nav-link" asp-controller="Games" asp-action="MineSweeper">Minesweeper</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="Games" asp-page="/Solitaire" asp-route-style="Klondike">Solitaire</a>
                <ul class="nav-menu">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Games" asp-page="/Solitaire" asp-route-style="Klondike">Klondike</a>
                    </li>
                </ul>
            </li>
            @*
                <li class="nav-item">
                    <a class="nav-link" asp-area="Games" asp-controller="Games" asp-action="Index">Test Item</a>
                    <ul class="nav-menu">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Games" asp-controller="Games" asp-action="Index">Test Item</a>
                        </li>
                    </ul>
                </li>
            *@
        </ul>
    </li>

    @*@if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <a class="nav-link" asp-area="ResumeBuilder" asp-controller="Resumes" asp-action="Index">Resum&eacute;</a>
            <ul class="nav-menu">
                <li class="nav-item">
                    <a class="nav-link" asp-area="ResumeBuilder" asp-controller="Resumes" asp-action="Edit">Edit</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="ResumeBuilder" asp-controller="Resumes" asp-action="View">View</a>
                </li>
            </ul>
        </li>
    }*@

    @if (showAboutMenu)
    {
        <li class="nav-item">
            <a class="nav-link" asp-controller="Home" asp-action="Index">About</a>
            <ul class="nav-menu">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index" asp-fragment="gameDesign">Game Design</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index" asp-fragment="webDev">Web Development</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index" asp-fragment="software">Home Software</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index" asp-fragment="worldBuilding">World Building</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Social Media</a>
                    <ul class="nav-menu">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index" asp-fragment="twitch">Twitch Channel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index" asp-fragment="youtube">Youtube Channel</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index" asp-fragment="patreon">Support Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-page="/Home/Team">Meet the Team</a>
                </li>
            </ul>
        </li>
    }
    <li class="nav-item">
        <a class="nav-link" asp-page="/Home/Contact">Contact Us</a>
    </li>
</ul>